#+TITLE: nomnichi_bot
#+AUTHOR: Y.Kimura
#+EMAIL:
#+DATE: Created 2011-06-09
#+OPTIONS: H:3 num:2 toc:nil
#+OPTIONS: ^:nil @:t \n:nil ::t |:t f:t TeX:t
#+OPTIONS: skip:nil
#+OPTIONS: author:t
#+OPTIONS: email:nil
#+OPTIONS: creator:nil
#+OPTIONS: timestamp:nil
#+OPTIONS: timestamps:nil
#+OPTIONS: d:nil
#+OPTIONS: tags:t
#+TEXT:
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE: ja
#+LATEX_CLASS: jsarticle
#+LATEX_CLASS_OPTIONS: [a4j]
# #+LATEX_HEADER: \usepackage{plain-article}
# #+LATEX_HEADER: \renewcommand\maketitle{}
# #+LATEX_HEADER: \pagestyle{empty}
# #+LaTeX: \thispagestyle{empty}

* nomnichi_bot
** What is nomnichi_bot?

  Nomnichi is a blog of nomura-laboratory's students.
  (http://www.swlab.cs.okayama-u.ac.jp/lab/nom/nomnichi)

  nomnichi_bot tweets us who is expected to write
  a new nomnichi blog article as a reminder.

  To use this application, you needs these setup:
  1) Twitter credencial as _twitter_auth.stg
  2) Redmine credential as _redmine_mail.stg
  3) Member list of the labo as nom_table.rb

** Functions

   1) Remind next nomnichi author
   2) Inform today's weather in Okayama
   3) Inform kinro (TV show) title
   4) Remind group schedule

** INSTALL for developers:
   1) Install rbenv + ruby-build
      (see https://github.com/sstephenson/rbenv#basic-github-checkout for details)
      #+BEGIN_SRC shell-script
        $ git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
        $ git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
        # Edit your shell dot files to add some path and environment variables.
      #+END_SRC

   2) Install Latest Ruby and bundler
      #+BEGIN_SRC shell-script
        # Install ruby 2.1.2
        $ rbenv install 2.1.2

        # Installation check
        $ rbenv global 2.1.2
        $ ruby -v # -> You will see: ruby 2.1.2...

        # Install bundler for your new Ruby
        $ gem install bundler

        # Get back to your sytem default Ruby if you want
        $ rbenv global system # say, /usr/bin/ruby
        $ ruby -v
      #+END_SRC

   3) Clone nomnichi_bot from github
      #+BEGIN_SRC shell-script
        $ git clone git@github.com:nomlab/nomnichi_bot.git ~/src/nomnichi_bot
      #+END_SRC

   4) Set default ruby version in nomnichi_bot project
      #+BEGIN_SRC shell-script
        $ cd ~/src/nomnichi_bot
        $ echo '2.1.2' > .ruby-version
        $ ruby -v # -> You will see: ruby 2.1.2...
      #+END_SRC

   5) Install requied gem packages in sandbox ~/src/nomnichi_bot/vendor/bundle
      #+BEGIN_SRC shell-script
        $ cd ~/src/nomnichi_bot
        $ bundle install --path vendor/bundle
      #+END_SRC

   6) Place OAuth credentials as _twitter_auth.stg
      #+BEGIN_SRC shell-script
        # This file is expected to contain four lines:
        $ cat ~/src/nomnichi_bot/_twitter_auth.stg
        consumer_key
        consumer_secret
        access_token
        access_token_secret
      #+END_SRC

   7) Check if nomnichi_bot is alive.
      #+BEGIN_SRC shell-script
        $ ~/src/nomnichi_bot/bin/nomnichi_bot TEST
      #+END_SRC

   You may add ~/src/nomnichi_bot/bin directory to your $PATH for dogfooding
